#include <iostream>
#include <string>
using namespace std;

int main(){
    /*
        I mean what did you expect it's just a cout of a really long string
    */

    string doge = 

    string("000OOOOOOOOOOOOOOOOOOkkkkkkkkkkkkkOOOOOOOO000000000000000000OOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOOOOOkkkkkkOOOOOOOOOOOO0OO00000KKKKKKKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX") + '\n' + 
    string("OOOOOOOOOOOOOOOOOOOOOOOkkkkkkkkkkOOOOOOOOO0000000000000000OOOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOOkkkkkkkkkOOOOOOOOOOO0OOO00000KKKKKKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX") + '\n' + 
    string("OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0000000000000000OOOkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOOOOOOkkkkxxxxxxkkkOOOOOOOOOOOOO0000KKKKKKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX") + '\n' + 
    string("OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO00000000OOOO000OOOkkkkkkkkkkkkkkkkkkkkkkkOOOOOOOOOOkkkkkkxxdddddddxxkkkkOOOOOOOOOOOO000KKKKXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXXKKKKKKKKKKKKKKKKKXXKKK0000KKKXXXKKKKKKKKKKKKKKKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX") + '\n' + 
    string("OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO000000OOOOOOOOOOOkkkkkkkkkkkkkkkkkkkkkkkOO000Okdollllolllcc:cccccc::cccclodxkxdolllllllooxkOOkxoolllloodddddooodxxxxdoodxk0K0kxdooddxxxdooodxkkdoooooooodkOOxdoooododdooodxk0KXXXXXXXXXXXXXXXXXXXXXXXXXXXXKKKKKKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX") + '\n' + 
    string("0OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkOOOOOOkkkxkkkkkOOOOOOOOkkkkkOOO0000kloO000Kk:;x0000k:.:k0000000Ol:ccd00000000OOxoc:lOK000000KOc:kKK000d;;xKKK0xlxOxox000KOc,d000KOl;cxOKXXXXKOxl::o0K00Kx:o00000xlx0XXXXXXXXXXXXXXXXXXKKKKK000000000000KKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX") + '\n' + 
    string("0OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkkkOOOOOOOkkkkkOOOOOOOOOOOOOOOO0000KK0x:lXMMMMKclNMMMNd..cXMMMMMMMNo',;xWMMMMMMMMMMXo.:KMMMMMMMMXc;0WMMMMX:'kWMMWk:oOx:oXMMMNl;OMMMWk,:0WMMMWWMMMWKl.lXMMMM0:dWMMMWk;l0XXXXXXXXXXXXXXXXXKK0OOOOOkkkkkkkxxxkO0KKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX") + '\n' + 
    string("0OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkkkkOOOOOOOOkOOO0000000OO00000000KKKKK0x;lXMMMMKd0MMMWO,..dWMMMMMMMWk,.,xWMMMW0kXMMMMO';0MMMMW0xkx;;0MMMMMWk:xWMMWx;lOOc;kWMMWkdXMMMK:'kWMMMWxdNMMMMO,cXMMMM0:dWMMMWx;l0XXXXXXXXXXXXXXXKK0OkkxxxxxxxxxdddooddxO0KXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX") + '\n' + 
    string("OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkkkkkkOOOOOOOOOO000000000000000KKKKKKKKKKx;lXMMMMNXWMMMXc..'kWMMMWMMMM0;.'xWMMMWx:OMMMM0,,0MMMMXc..,':0MMMMMMNkOWMMWx;l0Kx;cKMMMNXWMMNd.,0MMMMNc:KMMMMK:cXMMMM0:dWMMMWx;l0XXXXXXXXXXXXXXKK0OkkxdddddddddoooolllodkOKKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX") + '\n' + 
    string("0OOOOOOOOOOOOOOOOOOOOOOOOOOOkkkkkOOOOOOOOOOOOOkkkkkkkkOOOOOOO00000000000000KKKKKKKKXXXXKx;lXMMMMMMMMMNd'..:KMMMWXNMMMXl..xWMMMW0kXMMMWk';0MMMMNkloo,;0MMMMMMMNNWMMWx;l0KOl;xNMMMMMMM0;.;0MMMMNc:KMMMMK:cXMMMM0:dWMMMWx;l0XXXXXXXXXXXXKK0OOOkkxddooooooooollllclloxOKKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX") + '\n' + 
    string("0OOOOOOOOOOOOOOOOOOOOOOOOOOkkkkkkkOOOOOOOOOOOkkkkkkkOOOOO00000000000000000KKKKKKKKKXXXXKx;lXMMMMMMMMMXc.'.lNMMMXk0MMMWd..xWMMMMMMMMMWO;.;0MMMMMMMM0;;0MMMMMMMMMMMMWx;o0XKk::0MMMMMMNo'.;0MMMMNc:KMMMMK:cXMMMM0:dWMMMWx;l0XXXXXXXXXXXK00OkkkkxxddooooooooollllccclodOKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX") + '\n' + 
    string("OOOOOOOOOOOOOOOOOOOOOOOOOOkkkkkkkkOOOOOOOOOOkkkkkkkOOO0000000000000000000KKKKKKKKKKXXKKKx;lXMMMMMMMMMWx'.'xWMMM0cxWMMMO'.xWMMMMX0NMMWKl.;0MMMMWNKKk,;0MMMMMMMMMMMMWx;o0XK0o;oNMMMMWk;,,:0MMMMNc:KMMMMK:cXMMMM0:dWMMMWx;l0XXXXXXXXXKK0OOkkkxxxddddddddooolccc::::ccldOKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX") + '\n' + 
    string("OOOOOOOOOOOOOOkkkkkkkOOOkkkkkkkkOOOOOOOOOOOkkkkkkkOOO0000000000000000000KKKKKKKKKKXXXKK0x;lXMMMMWWMMMMXc.'OMMMMXk0WMMMK:.dWMMMWx:OMMMM0,;0MMMMNo';:':0MMMMWNWMMMMMWx;o0XXKk::0MMMMXl,c;:0MMMMNc:KMMMMK:cXMMMM0:dWMMMWx;l0XXXXXXXKK0OOkkkxxddddddddddooollc::::::::cldOKKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX") + '\n' + 
    string("OOOOOOOOOOOOOOkkkkkkkkkkkkkkkkkOOOOOOOOOOOOOOOOOOOOO0000000000000000000KKKKKXXXXXXXXXKK0x;lXMMMMXKNMMMWk';KMMMMMMMMMMMNo'dWMMMWx:OMMMM0;,0MMMMXl.,:,:0MMMMXk0WMMMMWx;l0XXKOc;OWMMMKc;o::0MMMMNc:KMMMMK:cXMMMM0:dWMMMWx;l0XXXXKKK0OOOkkxxdddddddddddddoollcc::::::::cldk0KXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX") + '\n' + 
    string("OOOOOOOOOOOOOkkkkkkkkkkkkkkkkOOOOOOOOOOOOOOOOOOOOO000000K000000KK00000KKKKKXXXXXXXXXXKK0x;lXMMMMKd0MMMMXooNMMMMNO0WMMMWk,dWMMMWx;OMMMM0;,0MMMMWKkOOlc0MMMMXllXMMMMWx;o0XXXOc;kWMMMK:;dl:kWMMMWkxNMMMMO,;KMMMMXx0WMMMNx;d0XXXK00OOOOkkxddddddddddddddddoollccc:::cc:ccldOKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX") + '\n' + 
    string("OkkOkkkkkkkkkkkkkkkkkkkkOOOOOOOO0000000000000000000KKKKKKKKKKKKKKKKKKKKKKXXXXXXXXXXKKKK0x:lXMMMMKcoNMMMWKKWMMMWk':XMMMMKcxWMMMWx:OMMMM0;;0MMMMMMMMWkc0MMMMNl'xWMMMWx:o0XXKOl:OWMMMKc:xxcc0WMMMWWMMMWKl',dXMMMMWMMMMWOcckKXKK0OOOOkkkxddooddddddddddddoooolllllccc:::ccldOKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX") + '\n' + 
    string("OkkkkkOkOkOOOOOOOOOOOOOOOOO00000000000000000000KKKKKKKKKKKKKKKKKKKKKKKXXXXXXXXXXXXXKKKK0kllxOkkOd,,dOkkkkkkkkkkl.,dkkkkx:ckkkkkl,okkkkd;;dOkkkkkkOkl:dOOkOkc':kOOOkocxKXXK0dcdOOOOxclO0xlcok0KXXK0koccoocldk0KXXK0koclk0KK0Okkkkkkxxdoooooodddoooooooooooolllllc::::::cldOKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX") + '\n' + 
    string("OOOOOOOOOOOOOOOOOOOO00000000000KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXKKXXXXKXXXXKKKKKKKK00xoc:;;;::::;,,,,,,,,,,;;;,,'',,,,,,',,,,,,,,;::::;;;;;;;:cclccc:clodolc::lok0KXXXKOxocc:codOKXK0kolcccccccoxOKKOxlccccccclok0K00Okkkkkxxxdoooooddoooooooooooooooolllllcc::::::cox0KXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX") + '\n' + 
    string("0OOOOOOOOOO0000000000000KKKKKKK00000KKKKKKKKKKKKKKKKKKKKK0000000KKKKKKKKKKKKKKKK0000000OOOkkxxdddddoolllllllooooooooooodoooooooooodddddxxddddddddxkkkkkkkkkOOOOOO00KKKKKKKKK0000000KKKKKKK00OOOOO00KKKKK00OOOOOOO00000Okxxxxxxddoolccllooooooooolllllccclllccccc::::::::cok0KKKKKKXXXXXXXXXXXXXXXXXXXXXXXXXX") + '\n' + 
    string("000000000000000KKKKKKKKKKKKK0OxdoooodddddooodxxxdooodxkxdoloooolodxOkxdoooodooooloooooolcccccccc::::;;;;;:::::::::::cllclccc::::ccclodxdolcc::::cclooolllccccccllloxkkxdolloodxOkxdoolllloodxk0KXXK0kdoooooolodkOOkdolc::::::::cc:;;;;;;;;;:::;;;,,,,,,;;;;;;,,,;;,,;,,,;:codooodxOKXXXXXXXXXXXXXXXXXXXXXXXX") + '\n' + 
    string("K0000KKKKKKKKKKKKKKKKKKKKKKKOooO0000kc;x0000x:,o0000x:;lxOKXXXXK0koc:oO0000x:o00000d;o000000000dlk00000000kld000000000l;d0000000OOkdcclc:d00000000d;,:lx0000000OOxdc:::d00000d:cccx000000000dcdO0OxloxOKXXXXKOxoc:cx0000000OOko:'':k00000000OO00000000000OooO0000o':k000Ol';kK000dokKXXXXXXXXXXXXXXXXXXXXXXX") + '\n' + 
    string("KKKKKKKKKKKKKKKKKKKKKKKKKKKKx:lXMMMMK;'OWMMMNl.dWMMWO,:KWMMMWWMMMMXl.lNMMMM0;dWMMMWx,dWMMMMMMMMOoKMMMMMMMMXdkMMMMMMMMNo,kMMMMMMMMMMWKc,';OMMMMMMMWO,.,lOWMMMMMMMMMWKl.'xWMMMWk,,,;OMMMMMMMMWd,cdxl;oXWMMMWWMMMWXo.,OMMMMMMMMMMW0:.cXMMMMMMMMWWMMMMMMMMMMMWkkWMMMWx.:XMMMM0,,0MMMNd:dKXXXXXXXXXXXXXXXXXXXXXXX") + '\n' + 
    string("XKKKKKKKKKKKKKKKKKKKKKKKXXXKx:lXMMMMK;'kWMMMM0:oNMMWk,oWMMMNxdXMMMWx.cXMMMM0;dWMMMWd'dWMMMMXkxxllKMMMMNOxkdckWMMMWKkxx:,kWMMMWOkNMMMWx'.:KMMMMMMMMK:.,cOWMMMWOkXMMMWk'.xWMMMWk,,,;OMMMMWKkxxl;ldo;:0MMMMXdoXMMMM0,'kWMMMWOkNMMMWx.:XMMMMNOxxxxxx0WMMMMNOxdlxWMMMWx.:XMMMMWd:OMMMNd;dKXXXXXXXXXXXXXXXXXXXXXXX") + '\n' + 
    string("XKKKKKKKXXXXXXXXXXXXXXXXXKKKx;lXMMMMK;'kWMMMMWkkNMMWk;dWMMMNdck0000o.cXMMMMO;dWMMMWd'dWMMMWx....cXMMMMK;...,kWMMMWo..'.,OWMMMNo:KMMMWk'.lNMMMMWMMMNl.'cOWMMMNo;0MMMM0,.xWMMMWk,,,;OWMMMNo..';lddl,cKMMMMK;,0MMMMK:'kWMMMNo:KMMMWk':XMMMMK;......cXMMMM0;...dWMMMWx.:XMMMMMXx0MMMNd;dKXXXXXXXXXXXXXXXXXXXXXXX") + '\n' + 
    string("XKXKKKKXXXXXXXXXXXXKKKKKKKKKx;lXMMMMK;'kMMMMMMWNWMMMk,cXMMMMWKkl,',,.lXMMMM0;dWMMMWd'dWMMMW0oll,cXMMMMXxll:;kWMMMWOlll,,kWMMMWOkNMMMWd..xWMMMNXWMMWx.'ckWMMMWOkXMMMNx..xWMMMWk,,,;OWMMMWOlloccodc'cKMMMMK;,0WWWWX:'kWMMMWOkNMMMWd.:XMMMMXxllc,..cXMMMM0;...xWMMMWx.:XMMMMMWNNMMMNd;dKXXXXXXXXXXXXXXXXXXXXXXX") + '\n' + 
    string("XXXXXXKXXXXXXXXKKKKKKKKKKKK0d;lXMMMMK;'kMMMMMMMMMMMMO,.oKWMMMMMWKxc'.lXMMMMO;dWMMMWd'dWMMMMMMMNocKMMMMMMMWk:kWMMMMMWWXc,kWMMMMMMMMMNx,.,OMMMWOkNMMM0,'ckWMMMMMMMMMNk;..xWMMMWk,,,;OMMMMMMMMXo;ldc'cXMMMMK;.:lcclc''kWMMMMMMMMMNx'.:XMMMMMMMWO,..cXMMMMK;...xWMMMWx.:XMMMMMMMMMMMNd;dKXXXXXXXXXXXXXXXXXXXXXXX") + '\n' + 
    string("XKXXXKKKKKKKKKKKKKKKKKKKKK00d;lXMMMMK;'kMMMMMMMMMMMMO,..'cxKWMMMMMXl.cXMMMMO;dWMMMWd'dWMMMMNXK0ccXMMMMWXKKd:kWMMMMNKKO:,kWMMMWKKWMMW0:.:XMMMNooXMMMXc':kWMMMWK0NMMMNk,.xWMMMWk,,,;OMMMMMNKK0l;odl'cXMMMMK;..'''''.,kWMMMWKKWMMW0:.:XMMMMWXKKx,..cXMMMM0;...dWMMMWx.:XMMMMMMMMMMMNd;dKXXXXXXXXXXXXXXXXXXXXXXX") + '\n' + 
    string("XKKKKKKKKKKKKKKKKKKK0000000Od;lXMMMMK;'kMMMWNNMMMMMWO,;ddodkkOWMMMM0;cXMMMMO;dWMMMWd'dWMMMWk;,,'cXMMMMKc',',kWMMMWx,,;',OWMMMNocKMMMWk'oNMMMWOONMMMWd;:kWMMMNo:0MMMMXc.dWMMMWk,,,;OWMMMWd,,:clddl'cKMMMMK;,kXXXX0:'kWMMMNocKMMMWk':XMMMMKc.'''..cXMMMM0;...dWMMMWx.:XMMMWNWMMMMMNd;dKXXXXXXXXXXXXXXXXXXXXXXX") + '\n' + 
    string("XKKKKKKKKKKKK000000000OOOOOko,lXMMMMK;'kWMMNOOWMMMMMk,oNMMMNc,OMMMMK:cXMMMMO;dWMMMWd'dWMMMWk,;:,cXMMMMK:':;;kWMMMWd..,',OWMMMNo:0MMMMO:xWMMMMMMMMMMMOcckWMMMNo;OMMMMNl.dWMMMWk'..,OMMMMWd.';clddl,:KMMMMK;,KMMMMK:'kWMMMNo:0MMMMO':XMMMMK:..''..cXMMMM0;  .dWMMMWx.:XMMMXkKMMMMMNd;dKXXXXXXXXXXXXXXXXXXXXXXX") + '\n' + 
    string("KKKKK0000000000OOOOOOOOkkkkko,lXMMMMK;'kWMMNdc0MMMMMk'cXMMMWxoKMMMMK;;KMMMMXxOWMMMNo'dWMMMWk,:l,cXMMMMKc,c;;OWMMMWKkkOo:kMMMMNo:0MMMMOl0MMMMW0ONMMMMKdcOWMMMW0kNMMMMXc.dWMMMMXOkxlOWMMMWKkkOxccol,;OMMMMXddXMMMMO''kWMMMNo:0MMMWk':XMMMMN0kkkc..cXMMMM0;  .dWMMMWx.:XMMMKcoNMMMMNd;dKXXXXXXXXXXXXXXXXXXXXXXX") + '\n' + 
    string("K00000OOOOOOOOOkkkkkkkkkxxxxl,lXMMMMK;'kWMMWd.oNMMMMO''xNMMMWWMMMMNx'.oXWMMMWWMMMWO,.xWMMMWk;:l;lXMMMMKc;c:;OMMMMMMMMMOckWMMMNo:KMMMWOxXMMMMX:'kMMMMNOd0WMMMMMMMMMMWO,.xWMMMMMMMXxOWMMMMMMMM0:;ooc,lKWMMMWWMMMWKc.'OMMMMNo:KMMMMO,:XMMMMMMMMNd..lXMMMMK;. .xWMMMWx.:XMMMK:'OWMMMNd:dKXXXXXXXXXXXXXXXXXXXXXXX") + '\n' + 
    string("0OOOOkkkkkkkkkkxxxxxxxxdddddl;cxkkkkd,'okkkkc.,dkkkko,.,lxOKKXKKOxl;::;cdk0KXXK0ko;,;okOkOOo:ldccxOkkOxccol:dkkkkkkkkko:okkkkkc;dkkkkdoxkkkOx;.lkkkkkdodkkkkkkkkkkxo:',lkkkkkkkkxlokkkkkkkkkd::oddc;:ok0KXKK0ko:,';okkkkx:,dkkkko';xkkkkkkkkkc..:xkkkko'...ckkkkkl.;xkkkx,.:kkkOkolkKXXXXXXXXXXXXXXXXXXXXXXX") + '\n' + 
    string("Okkkkxxxxxxxxxddddddddoooooolc;,,'',,;;;,'',;;;;,,,,:cllc;;:::::::ldkkxoc::::::::ldxdl:;;;:ldkkxoc:;;:cldxxoc;,,,,,,,;;;;,,,,,;;;,,,,,,;,,,;::::;,,,;;,,,,,,,,,,,,;:cll:;,,,,,,,;;;;,,,,,,,;:lodxxxoc:;;;;;;;;:looc:,'''''.'...',,,,'''''''',,,,'...............'',,,,'',,,,,',;cok0KXXXXXXXXXXXXXXXXXXXXXXX") + '\n' + 
    string("kxxddddddddddoooooooooooloolllllllllllllllllooooooddxxkkkkxxxxxxkOOO00OOOOkxxxxkkOOOOOkkkkkOO000OOkkkkkkkkkkxxdddddoooooooooooooooooodddddddddxddddddddddddddooodddxxxxxddddddddddddddddooddxxxxxxxxxdddoooooddxxxxdoollcc:::::::ccclccccccccc::;,'........''',;::ccllllllllllldO0KXXXXXXXXXXXXXXXXXXXXXXXXX") + '\n' + 
    string("xooooooooooooooolllllllllooooooooooooooooooodddxxxkkOOOOOOOO00OO000000000000OOOOOOOOOOOOO0000000OOOOOOOkkkkkkxxxxxxddddddddddddddddddxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxdddxxxxxxxddxxxxxkkxxxxxxxxxxxxxxxxxxxxxxdoolc::::::clllllllcccc:;,.........''',;::cclooolloooloox0KKXXXXXXXXXXXXXXXXXXXXXXXXX") + '\n' + 
    string("dllllllllllllllllloooooooooooooooooooooooddddxxkkkOO000OOOOO00000000000000OOOOOOOOOOOO00000000000OOOOOkkkkkkxxxxxxdddoooodddddddddxxxdxxxxddxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxdddxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxdolccccccllllllllccc;,..........'''',;::clooolooooooodx0KKXXXXXXXXXXXXXXXXXXXXXXXXX") + '\n' + 
    string("ollllllllllllooooooooooooooooooooooooodddddxxkkkOO0000000O000000000000000OOOOOOOOOOOO000000000000OOOOOkkkkkxxxxddddooooodddddxxxxxxxddxxxdddxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxdxxxxxxxxxxxxxxxxxxxxxxxxxxxkkkxxdollccclllllllllc:,'............'',;;:cloooooooooooodk0KKXXXXXXXXXXXXXXXXXXXXXXXXX") + '\n' + 
    string("olllllllloooooooooooooooooooooodddddddddxxkkkOOO0000000000000000000000000OOOOOOOOOO0000000000000OOOOOkkkkkxxxxddddoooodddxxxxxxxxxxddddxxxddddxxxxxxxxxxxxxxxxxxxkxxkkxxxxxxxxxxxxxxxxxxxdddxxxxxxxxxxxxxxxxxxxxxxxxxxkkxxxxdolllllllllllc;,..............',;;:clooooooooooooodk0KXXXXXXXXXXXXXXXXXXXXXXXXXX") + '\n' + 
    string("dlllolooooooooooooooooooodddddddddddddxxkkOOO0000000000000000000000000OOOOOOOOOOO0000000000000000OOOOkkkkkxxxdddddoooddxxxxxxxdddddddxxxddddxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxddddxxxxxxxxxxxxxxxxxxxxxxxxxkkxxxxxxdooollllll:;'..............',,;::cloodddddooooooxOKXXXXXXXXXXXXXXXXXXXXXXXXXXX") + '\n' + 
    string("dlloooooooooooooooooooooodddddddddddxxxkOO00000000000000000000000000OOOOOOOOOOOO000000000000000000OOkkkkkkxxdddddoooddxxxxxxddddxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxkxxxxxxxxxxxxxxkkkxxkkkxxddoollc:,'..............',;;:ccloodddddooollodk0KXXXXXXXXXXXXXXXXXXXXXXXXXXX") + '\n' + 
    string("doooooooooooooooooooooooodddddddddxxxkkOO00000000000000000000000000OOOOOOOOOOO00000000000000000000OOkkkkkxxxdoooooodddxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxdxxxxxxxxxxxxxxxxkkkkkxxxxxxxxxxxkkkkkxxddolc;,.............'',;:cclooodddddooooolodk0KXXXXXXXXXXXXXXXXXXXXXXXXXXX") + '\n' + 
    string("doooooooooooooooooodddddddddddddxxxkkOO000000000000000000000000000OOOOOOOOOOO000000000000000000000OOkkkkxxxddooooodddddxxxxxxxxxxxxxxxxxxxxxxxxkkxxxxxxxxkkkxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxkkkkkxxddoc:;;;;,'.....',,,;:cclloooooddooooollodk0KKXXXXXXXXXXXXXXXXXXXXXXXXXX") + '\n' + 
    string("dooooooooooooooooddddddddddddddxxkkkOO000000000000000000000000000OOOOOOOOOOOO00000O00000000000000OOOkkxxxxddooooodddddxxxdxxxxxxxkkkkkkkkkkkkkkkkkxxxxxxkkxxxxxkkxxxxkkkkkxxxxxxxkkkxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxkkxxxkkkkxxddolllc:;'...',;:::cclllllloooooolllcclok0KKXXXXXXXXXXXXXXXXXXXXXXXXXX") + '\n' + 
    string("doooooooooooooddddddddddddddddxxkkOOO00000000000000000000000000OOOOOOkkkOOOOOOOOOOOO0000000000OOOOOkkxxxxxdddooodddxdddddxxxxxxkkkkkkkkkkkkkkkkkxxxxxkkkxxxxxxxxxxxxxkkkkkxxxxxxxkkkxxxxxxxxxxxxxxxxxxxxxxxxxxxxkkkkkkxxxxxxxxxkkkkkkxxxddooolc:;,,;:ccccllllllcllllllc::;;:coxO0KKXXXXXXXXXXXXXXXXXXXXXXXXX") + '\n' + 
    string("dooooooooooooddddddddddddddddxxkkOO000000000000O0000000000000OOOOOkkkkkkkkkkkkkkkOOOOO000OOOOOOOOOkkxxxxxxddoooddddddddxxxxxkkkkkkkOOOOOOOOkkkkkkkkkxxxxxxxxxxxxxxxxxxxxkkkkkxxxxxxxxxxxxxxxxxxxxkkxxxxxxxxxxxxxxxxkkxxxxxxxkkkkkkkkkkkxxxddoollcc:ccclllllloolllllc:;,',;:clodk00KKKXXXXXXXXXXXXXXXXXXXXXXX") + '\n' + 
    string("dooooooooooddddddddddddddddddxkkOO000000000000000000000000000OOOkkkkkkkkkkOOkkkkkOOOOOOO00OOOOOkkkkxxddddddooddddddddddxxdxkkkkOOOOOOOOOOOOOOOOkkkkkkkxxxxxxxxxxxxxxxxxxxxxkkxxxxxxxxxxxkkkkxxxxxxxkkkkkkxxxxxxxxkxxxxxxkkkkkkkkkkkkkkkkxxxxdddoollllllllooooooooooc;'',;clooodkO0KKKKKXXXXXXXXXXXXXXXXXXXXX") + '\n' + 
    string("dooooooooodddddddddddddddddxxxkOO00000000000KK000KKKK00000000OOOOkkkOOOOOOOOkkxkkkOOOOOO0OOOOOkkkkxxddddddoooddddddddddxxxkkkOOOOOOOOOOOOOOOOOOOkkkkkxxxxxxxxddddxxxxxxxxxxxxxxxxxxxxxxxxxxxxxkkxxkkkkkkkkkxxkkkkkkxxxxxxxxxkkkkkkkkkkkkkkkkxxxdddoollllloooooooddooc::cloddoodxOO00KKKKXXXXXXXXXXXXXXXXXXXX") + '\n' + 
    string("doooooodddddddddddddddddxxxxkkOO0000000000KKKKKKKKKKKKK0000OOOOOkxxxxxxxkkkOkkxxxxkkkOOOOOOOOOkkkxxddddddoooooooooooddxxxkkOOOOOOOOOOOOOOOOOOOOOOOOkkkxxxxxddddddxxxxxxxxxxxxxxxxxxxkkxxxxxxxxxxxxxkkkkkkkkkkkkkkkxxxxxxxxxxkkkkkkkkkkkkkkkkkkkxxxddoooloooooooooodoooooddddoodxkO00KKKXXXXXXXXXXXXXXXXXXXXX") + '\n' + 
    string("dooodddddddddddddddxxxxxxxxkkO0000000000KKKKKKKKKKKKKKK000OOOkxol::;;;,;;:coddxddxxkOOOOOOOOOkkkxxxddddddoodoooooodddxxkkkOOOO00OOOOOOOOkkOOOOOOOOkkkkkkkxxxxddddddddxxxxxxxxxxxxxxkkkkkxxxxxxxxxxkkkkkkkkkkkkkkkxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkxxxddooooooooooooooooooooooooxkOO00KKKXXXXXXXXXXXXXXXXXXXX") + '\n' + 
    string("xdddddddddddddxxddxxxxxxxxkOO000000000KKKKXXXXXXXXKKKKK000Okxdc,...........,:coddxxkOOOOOOkkkkxxxxxdddddddddddddddddxxkkkOOOOO00OOOOOOOkkOOOOOOOkOOkkkkkkkkxxxxxxxxdddxxxxxxxxxxxxxxkxxxxxxxxxxxxxkkkkkkkkkkkkkkkkxxxxxxxxxkkkkkkkkkkkkkkkOkkkOOkkkkkxxdoooollloooolllccccclooodxkOO00KKKKXXXXXXXXXXXXXXXXXX") + '\n' + 
    string("xdddddddddddxxxxxxxxxxxkkkOO00000000KKKXXXXXXXXXXXXKKKK00OOko;'.'''...     ..':lodxkOOOOkkkkkxxxxxxxxxxdddddddddddddxkkkkOOOOOOOOOOOOOkkkkOOOOOOOOOkkkkkkkkkkkxxxxdddddddxxxxxxxxxxxxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkxxxxxxkkkkkxxkkkkkkkOOOOOOOOOOkkkkxxddooolllooollcc::::ccllodxkOO00KKKKXXXXXXXXXXXXXXXXX") + '\n' + 
    string("xddddxxxxxxxxxxxkkkkkkkkOO00000000KKKXXXXNNNNNNNNXXXKK000Oxo:,;cc::lc'........,:coxkOOOkkkkxxxxxxxkxxxxxddddddxxdxxxxkkkOOOOOOOOOOOOOOkkkOOOOOOOOOkkkkkkkkkkkkkxxxddoooooddddddxxxxxxxxxxxxxxxxxxkkkkkkkkkkkkkkOkkkkkkxxxxxkkxxxxxxkkkkkkkkOOOOOOkOOkkkxxxddooooooollc:::::ccccldxkOO000KKKKXXXXXXXXXXXXXXXX") + '\n' + 
    string("kxxxxxxkkkkkkkkkkkkOOOOOO0000000KKKKXXXNNNNNNNNNNNXXKK00Okdlcldl;;cl;,'..'ldc'.';lxkOkkkkkxxxxkkkkkkkxxxxxxxxxxxxxxxxkkkOOOOOOOOOOOOkkkkkkOOOOkOkkkkkkkxxkkkkkxxxxddooolllooodddddxxxxxxxxxxxxxxkkxxxxkkkkkkkkkkkkkkkkkkxxxkkxxxkkkkkkkkkkkOOOOOOOOOOkkkkxxddoooooolllcc::ccccclodxkkOO00KKKKXXXXXXXXXXXXXXX") + '\n' + 
    string("OkkkkkkkkOOOOOOOOOOOOO000000KKKKKKKXXXNNNNNNNNNNNNXXKKK0Okxdxxl,.','......,,....;lxkkkkkkkkkkkkkOOOkkkkxxxxxxxkkkkkkkkkkkOOOOOOOOOOOkkkkkkkkkkxxxxxxxkkkxxxxxxxxxxdddoolllllloooddddxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOOOkkkkkxxddooooollllcc::::cclodxxkkOO00KKKKXXXXXXXXXXXXXX") + '\n' + 
    string("OOOOOOOOOOOO000000000000000000KKKKXXNNNNNNNNNNNNNXXXKKK0OxdxOx:................,:oxkkkkkkkkOOOOOOOOOOkkkkkkkkkkkkkkxxkkkkkkkkkOOOOkkkkkkkkxddollloooddxxxxxxxxdddxxxxdddooooooooodddddxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOkkkkkkkkxxddoooolcc::::::ccloodxxkkOO00KKKXXXXXXXXXXXXXX") + '\n' + 
    string("0O00000000000000000000000000000KKKXXNNNNNNNNNNNNXXXKKKK0koldOx:''''''...   ...,:odxkkkkkOOOOOOOOOOOkkkkkkkkOOOOkkkkxxkkkkkkkkkkkkkkxxxxxdl:;,''.'',,;:ccloodddddddxxxxxxddooooodddddddxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxxddoool::;;;;;::cloddxkkkOO0KKKXXXXXXXXXXXXXX") + '\n' + 
    string("00000000000000000000000K00000KKKXXXNNNNNNNNNNNNXXKKKKKKOxolokxc,',,,''...   .':odxxkkkOOOOOOOOOOOOkkkkkkOOOOOOOkkxxxxkkkxxkkkkkxxxxxddoc;......      ....,:clodxdddddxxxxddddddddddddddxxxxxxkkkkkkkkkkkxkkkkkkkkkkxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxxdddoolc;;,,;;:cclodxxkkOO00KKKXXXXXXXXXXXXX") + '\n' + 
    string("K000000000000000KKKKKKKK00KKKKXXXXNNNNNNNNNNNNXXXKKKKK0Oxollddl,'',,,''.....,cdxxkkkkOOOOOOOOOOOOkkkkkOOOOOOOOOkkxxxxxxxxxxxxxdddddol;'...',;;,..         ...,codooooodddddddddxxddddddxxxxxkkkkkkkkkkkkxxxkkkkkxxxkkkkkkkkkkkkkkkxxxkkkkkkkkkkkkkkkkkkkkkkkkkkxxxddooolc;,,,,;:cloddxxkkOO00KKKXXXXXXXXXXXX") + '\n' + 
    string("K0000000000KKKKKKKKKKKKK00KKKXXXNNNNNNNNNNNNNXXXKKKK000Okdolll:,....'''..',coxkkkkOOOOOOOOOOOOOOOkkOOOOOOOOOOOkkkxxxxxxxddddoolllc:;'...;cdkkkOkxl,.         ..,cloooooddddddddxxxxxxxxxxxxxkkxxxkkkkkkkkkkkkxxxxxxkkkkkkkkkkkkkkkkxxkkkkxxxkkkkkkkkkkkkkkkkkkkkxxxddooolc:;,;;:cloodxxkkOO00KKKXXXXXXXXXXXX") + '\n' + 
    string("K00000000000000KKKKKKKK000KKKXXNNNNNNNNNNNNNXXXKKK00000Okxdolcc:;,''',;:cldkOOOOOOOOOOOOOOOOOOOOOOOOO0OOOOOOOkkxxxdddddddoooll:;,'....,cdkOkoc:loc,......      ..;cllllodddddddxxxxxxxxxxkkxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxxxxxkkkkkkkkkkkkkkkkkkkkkxxxxdooolc:::::cclodxxkkkOO00KKXXXXXXXXXXXX") + '\n' + 
    string("K000000000000000KKKKK0KKKKKKXXNNNNNNNNNNNNNNXXXKK00000OOOkkxdollcc::clodxkOOOOOOOOOOOOOOOOOOOOOOOOOO000OOOOOkkkxxdddooooollc:;'......;lxkkko;...............    ..';cllloddxxxxxxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxxxxkkkkkkkkkkkkkkkkkkkkxxxxxxddollcc:::cclodxxxkkOO00KKXXXXXXXXXXXX") + '\n' + 
    string("K00000000000000000KKK0KKKKKXXNNNNNNNNNNNNNNNXXKK0OOOOOOOOkkkxxddooodxkOOOO0OOOOOOOOOOOOOOO0000O00000000OOOOOkkkxxddooollcc:;'.......,lxkkxo:.......  .........  ....;clooodxxxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxxxxxxxxdoollcc::ccloddxxkkkOO0KKXXXXXXXXXXXX") + '\n' + 
    string("K000000000000000000KKKKKKXXXNNNNNNNNNNNNNNNXXXKK0OOOOOOOkkkkkkkkkkOOO0000OOOOOOOOOOOOOO000000000000000OOOOOOOkkkxxdolccc::;'....  .'coxxdo:'.          ............';loddddxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxkkkkkkkkkkkkkkkkkkkkxxxxxxxddoolcccccllooddxxkkOO0KKKXXXXXXXXXXX") + '\n' + 
    string("K000000000000K0000000KKKXXXNNNNNNNXNNNNNNNXXXXKK0OOOOOOOOOOOOOOOO000000OOOOOOOOOOOOOOO0000000000OOOOOOOOOOOOOOkkkxxdolllc:;,..... .':oddol;.....         .....',,,;codxxxxxxxxxxxkkkkkkkkkkkOOOOOOkkkkkkkkkkkkkkkkkOOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxxxxxxddollcclloooddxxxkkkO00KKXXXXXXXXXXX") + '\n' + 
    string("K00K0000000KKK0000000KKXXXNNNNNNNNXXNNNNXXXXXXKK0OOOOOOOOOOOO000000000OOOOOOOOOO0000000000000000OOOOOOOOOOOkOOkkkxxdddoollc:,.......,:lllc;'.......     .....,;;;codxkkkkkkkkkkkkkkOOOOOOOOOOOOOOOOkkkkkkkkkkOOOOOOOOOOOOOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxxxxxxxddoolllooodddxxxxkkO00KKXXXXXXXXXXX") + '\n' + 
    string("K0KKK0000000KKK000000KKXXNNNNNNNXXXXXNNXXXXXXXKK00OOOOOOOOO00000000000OOOOOOOO0000000000000000000O00OOOOOkkkkkkkkkxddooooool:,.......';:c::,...............,;::coxkkkkkkOOOOkkkkOOOOOOOOOOOO0000OOOOOOOOOOOOOOOOOOOOOOOOOOkkkkkOOOOOOOOOkkkkkkkkkkkkkkkkkkkkkkkkkxxxxxxxxxddoooooodddddxxxkkO00KKXXXXXXXXXXX") + '\n' + 
    string("K000000000000KKKKKKKKKXXXNNNNNNNNXXXXXNXXXXXXXKKK000OOOO000KKKK0000000000000000000000000000000000000OOOOOOkkkkkkkxxxddddddddoc;,,'....',;:c:'.........'''';:cldxkOOOOOkOOOOOOOOOOO0000000000000OO0000OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkkkOOOOOOOkkkkkkkkkkkkkkkkkkxxxxxxxxdddoddddddddxxxkkO0KKKXXXXXXXXXXX") + '\n' + 
    string("K0000000000000KKKKKKKXXXXXXXNNNNNXXXXXXXXXXXXXXKKKK000000KKKKK000000000000000000000000000000000000000OOOOOOkkkkkkxxxxdddddxxxddoolc:;,,,,;::;;;;::::;:::ccloxkkOOOOOOOkOOOOOOOOO00000000000000000000000000OOOOOOOOOOO00000OOOOOOOOOOOOOOOOOOOOOOOOOkkkkkkkkkkkkkkkkxxxxxxxxxdddddddddddxxxkkOO0KKXXXXXXXXXXX") + '\n' + 
    string("K0000000000000000KKKKXXXXXXXXXXNNNNXXXXXXXXXXXXXXXKKKKKKKKKK0000000OO00000000OOOOOOOO00O000000000OOO00OOOOOOOOkkkxxxddxddxxkkkxxxxxddoollcc::cccccclloddxxkkOOOOOOOOOOOOOOOOOO00000KKK0000000000000000000OOOOOOOOOOOO0000000000OOOOOOOOOOOOOOOOOOOOkkkOOOOOOOOkkkkkxxxxxxxxxdddddddddddxxxkkkO0KKXXXXXXXXXXX") + '\n' + 
    string("K00000000000000000KKXXXXXXXXXXXXXNNNXXXXXXXXXNNXXXKKKKXXKKK000OOOOOOO0000OOOOOkOOOOOOO00000000000OOOOOOOOOOOOOOkkkkxxxxxxxkkkkkkkxxxxxxxxxdddddddddxxkkkkOOOOkkkkkOOOOOOOOOO000000KKKK0000000000000000OOOOOkkOOOOOOOOOOOOOOOOO00OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkkkkkkkkkkxxxxxxdddddddddxxxxkkO00KKXXXXXXXXXX") + '\n' + 
    string("K00000O0000000000KKKXXXXXXXXXXXXXXNNNXXXXXXXXXXXXXXXKK00OOkkkkkkkkkOOOOOOOkkkkkkkOOOOOO00000000000000OOOOOOkkkkkOkkkxxxxxxkkkkkkkxxxxkkkkkkxxxxxxxxkkkkkkkkkkkkkkkOOOOOOOOO0000000000000000000000000OOOkkkOOOOOOOOOOOO00000000000O00OOOOOOOOOOO000OOOOOOOOOOOkkkkkkkkkkxxxxxxxxddddddxxxxxxxkOO0KKKXXXXXXXXX") + '\n' + 
    string("K00OOOOOOOO000000KKKXXXXXXXXXXXKXXXXXXXXXXXXXXXKK0OkxddooollooooooodddxxkkxxxxxkkOOOOOOO0000000000000OOOOOOOOOkkkkkkkkkxkkkkkkkkkkkxxxxxxxxxxxxxkkkkkkkkkkkxxkkkkkOOOOOOOO00000000000000000000000OOOOkkkkkOOOO0000000000000OOOO00OOOOOOOOOOOOO00000000OOOOOOOOOOkkkxxxxkkxxxxxxxxxxxxxxddxxxxkO0KKKXXXXXXXXX") + '\n' + 
    string("0OOOOOOOOOO00000KKKKXXXXXXXXXXXXKKXXXXXXXXKKK0Oxddollccccccclcccc:::cccclooddxxkkOOOOOOOOOO000000000OOOOOOOOOOOOOOkkkkkkkkkkkkkkkkkkkkxxxxxxxxkkkkkkkxxxxxxkkkkkkkkOOOOOOO000000000000000000000000OOkkkkkkkkOOOOOOO0000000OOOOOOOOOOOOOOOOOOOOOOO00000OOOOOOOOOOkkkxkkkkkxxxxxxxdddxxxxxxxxxxkO0KKXXXXXXXXXX") + '\n' + 
    string("0OOOOOOOOOOOO000KKKXXXXXXXXXXXXXXXXXXXXXXKKOdlccccc::;;;;:::::::::::;;;;;;;:lodxkkOOOOOOOOO000000OO0000OOOOOOOOOOOkkkkkkkkkkOOOOOkkkkkxxxkkkkkkkkkxxkkkkkkkkkkkkkOOOOOOOOO00000000000000000000000000OOOOOOOOOOOOOOOOOOO0OOOOOOOOOOO0000OOOOOOOOOOOOOO000OOOOOOOOOOkkkkkkkkkxxxxxxddxxxxxxxxxxkOO0KKXXXXXXXXX") + '\n' + 
    string("0OOkkkkkkkOOOOO00KKKXXXXXXXXXXXXXXXXXXXXK0x:,''...''.....''''',,,;:;,,''''',,;:codxkOO00000000000OO0000OOOOOOOOOOOOOkkkOOkkOOOOOOOOkkkkkkkkkkkxxxxxxxkkkkkkkkkkkkkOOOOOO000000000000000000000000KKKK00000000000000000000000000000000000OOO00O00000000000OOOOOOOOOOOOOkkkkkkkkxxxxxxxxxxxxxxxxkkO0KKXXXXXXXXX") + '\n' + 
    string("0OOOOOOkOOOOOO000KKKKKKKKKXXXXXXXXXXXXXK0d:.................................''',;cldxkO0000000000000KK000OOOOOOOOOOOOOkOOkkOOOOOOOOOOOOOOkkkkkkxxxxkkkkkkkkkkkkkkkOOOOOOO000000000000000KKKKKKKKKKKKKK0KKKKKK0000000000000000000000OOOOOO00000000000OOO0OOOOOOOOOOOOOOOOOkkkkkkxxxxxxxxxxxxxxkkO0KKKXXXXXXXX") + '\n' + 
    string("0OOOOOOOOOOOO000KKXXXKKKKKKKXXXXXXNNNXXKkc'...   .........           ...........'',;lxO0000000K0KKKKKKK00000OOOOOOOOOOkkkkkOOOO000000000OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO00000000000000000KKKKKKKKKKKKKKKKKK0000000000000000000000OOOOOOOO00000000OOOOOOOOOOOOOOOOOOOOOOkkkkkkkxxxxxxxxxxxxxkkOO0KKXXXXXXXX") + '\n' + 
    string("0OOOOOOOOOOOO00KKKKKKKKKK0KKKXXXXNNXXXXKx:...     ....                 ............':okO0000KKKKKKKKKKK000000OOOOOOOOOkkOOOOO000000000000000000000000OOOOOOOOOOOOOOOOOOOOO0000000000000000KKKKKKKKKKKKK00KKKK00000000000000000000000OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkkkkkkxxxxxxkkkkkkkkkkO00KXXXXXXXX") + '\n' + 
    string("OkOOkkkkkkkkOO00KKKKK00000000KKXXNNXXXKKOo,..     .....                 ..  .......,:oxO00KKKKKKKKK0KK00000000OOOOOOOOOOOOOOOOOOO0OO00000KK0000000000000OOOOOOOOOOOOO00000000000000000000000000KK000000000000000000000000000000000000000000000000000OOOOO00000OOOOOOOOOOOOkkkkkkkxxxxxxxkkkkkkkkOO0KKXXXXXXX") + '\n' + 
    string("kkkkkkkkkkkOO0KXXXXXXXKKKKK00KKKXXXXXKK0Odc;.     .......               ..   .....',:lxkO00000KKKK00000000000000OOOOOOOOOOOOOOOO0000000000000000000000000000000OOOOOOO00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000OOOOOOOOOOOkkkkkkkkkkxxxxxkkkkkkkkOO0KKXXXXXX") + '\n' + 
    string("kxkkkkkkOOOO0KXXXXXXXXXKKKKKKXXXXXXXKK0Oxdll:'............               ... .....';:ldkO00000000000OOO0000000000OOOOOOOOOO00OOO00000000000000000KKKKKK000000000000000000000000000000000000000000000000O000000000000000000000000000KKKKK00000000000000000OOOOOOOOOOOOOOOOOOOOOkkkkkkkxxxkkkkkkkkkkO00KKXXXXX") + '\n' + 
    string("kxkkkkOOOOO00KXXXXNXXXXXXXXXXXXKKKKKK0Okdlccc:,''.........                     ...';coxkOOO00000000000000000OOOOOOOOOOOOOO0000OO0000000000000000000000000000000000000000000000000OOOOOO000000000000000000000000OOOOOOOOOOO000000KKKKKKKK0000000000000000000OOOOOOOOOOOOOOOOOOOkkkkkkxxxxkkkkkkkkkkOO0KKKXXXX") + '\n' + 
    string("kkkkkkOOOO00KKXXXXXXXXXXXXXXXXXXKKK00Okxo:,................    ...             ...,:ldxxkOOOO000000000000000000OOOOOOOOOOOO00OO0000000000000000000000KK00000000000000000000000000OOOOOO000000000000000000OOOOOOOOOOOOOOOO000000000000KK000000000000000000000OOOOOOOOOOOOOOOOOOOkkkxxxxxkkkkkkkkkkkkO0KKKKXXX") + '\n' + 
    string("OkkkkkOOOO00KXXXXXXXXXXXXXXXXXXXKKK00Okxdc,...........  ....    .......     ...'',;coxxkkkOO00O00000OOO0000000OOOOOOOOOOOOOO00000000000000000000000KKKK000000000000000OOO000000000000000000000000000OOOOOOOOOOOOOOOOOOO0000000000000000000000000000000000000OOOOOOOOOOOOOOOOOOkkkkkxxxkkkkkkkkkkkkkOO0KKKXXX") + '\n' + 
    string("OkkOkkkOOO00KXXXXXXXKKKKKKKKKKKKK00OOkkxdl:'..........  ......      ..........',;;:ldxxkkkkOOOkkkOOOkkkOkkkkOOOkkkkkkkkkOOOOOOOOO0000000000000000000000000KKK000000000000000000000000000000000000OOOOOOOOOOOOOOOOOOOOOO0000000000000000000000000000000000000OOOOOOOOOOOOOOOOkkkkkkkxxxxkkkkkkkkkkkkkO0KKXXXX") + '\n' + 
    string("OkkkkkkkOO0KKKXXKKKK000000000000000OOkkxdlc:,.........   ........       ....'',;:ccldxkkkxxkkxdddkkkkkkOkxxkkOkkkkkkkkkOOOOOOOOOOOOOOOO000000000000000000000000000000000000000000000000000000000OOOOOOOOOOOOOOOOOOOO000000000000000000000000000000OOOOOOOOOOOOOOOOOOOOOOOOkkkkkkxxxxxxxxxkkkkkkkkkkkOO0KKKXX") + '\n' + 
    string("OkkkkkOOOO000KKKKKKKKKKKKKKK0000OOOOkkxdolc:;,'.......   ...........  ....'',;:clllodxkkxodxkkxxxkOOOOOOOOO00OOOOOOkkkkOOO0000000000000000OOOOOOO000000000000000000000000000OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO00000000000000000000000OOOOOOOOOOOOOOOOOOOOOOOOOOOkkkkkkkkkxxxxxxdxxxxkkkkkkkkkkkOO00KKXX") + '\n' + 
    string("OkkkkOOkOOO000KKKKKKXXXKKKKK000OOOkkxxdoolc::;,'......   ..............',,,,,;:looodddxkxxxkkOOOOOOOOO000000OOOOOkkkkkkkOOO0000000000000O00OOOOOOOOOOOOO0000000000000K000000000OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0OOO00000000000000OOOOOOOOOOOOOOOOOOOOOOOOOOOkkkkkkkkkkkxxxxxxxdxxxxxkkkkkkkkkkOOO0KKKX") + '\n' + 
    string("OkkkOkkkkOO00KKKXXXXXXKKKKKK0000OOkkxdollcc::;;,''....................',,,,,;:cloddlldxkkkkOOOOO0OOOOOOOOOOOOOkkkkkkkkkkOOOO0000000OO00OOOOOOOOOOOOOOOOOOOO000000000000000000OOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0000000000O00000000000OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkkkkkkkkkkxxxxxddddxxxxxxxkkkkkkkkkOOO0KKKK") + '\n' + 
    string("OkkkkkkkkO00KKXXXXXXXKKKKKKK000OOOkkxdollc:;;,,,,''...................''',;::::lodxxxxkkkkOkkxkkkkxxkkkkkkOOkkkkxxkkkkkkkkOOO00000OOOOOOOOOOOOOOOOOO0OOOOOOOOO000000000000000OOOOOOOOOOOO00OOOOOOOOOOOOOOOO000000000000000000OOOOOOOOOOOOOOOOOOOOOOOOOOkkkkkkkkkkkkkkkkkkkkxxxdddddddxxxxkkkkkkkkkkkkOO00KKK") + '\n' + 
    string("OkkkkkkkOO00KKXXXXXXXXKXKKKK00OOOkkxddolc::;;;;,,,'''................'',,;;::clooodxxxddxxkdlldxkxddxxxxxkkkxxxkkkkkkkkkkkkOOOOOOOOOOOOOOOO000OOOOO000OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0000000000000OOOOOOOOOOOOOOOOOOOOOOOOOOOOkkkkkkkkkkkkkkkkkkkkxxxddddddddxxxxxxxxxxkkkkkOOO00KK") + '\n' + 
    string("OkkkkkkOOO00KKXXXXXXKKKKKKKK000OOkkxdolllc:;;;;;,,,,,'...'''''''......'',,,;:cc::coddlcloxxolodxkxxkkkxxkkkkkxxkkkkkkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkkOOOOOOOOOOOOO0OOOOOOOOOOOOOOOOOOOOOkkkkkkkkkkkkkkkkkkkkkkkkxkkkkkkkxxxxddddddddxxxxxxxkkkkkkkkkkkO00K") + '\n' + 
    string("OkkkkkkOO00KKKKKXXXKKKKKKKKKKK0OOOkkxddolc:::;;;;,,,,,,''',,'''''....'''''',:clcclodddddxxxxkxxxkkkkkkkkxkkkkkkkkkkkkkxxkkkkkOOOOOOOOOOOOOOkkkkOOOOOOOOOOOOOOOOOOkkkkkkkOOOOOOOOOOOOOOOOOOkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkkkkkkkkkOOOOkkkkkkkkkkkkkkkkkkkxxxxxddddddddddxxxxxxxxxkkkkkkkkOO00K") + '\n' + 
    string("OkkkkkOOOO00KKKKXXXXXXXKKKKKK00OOOOkxddolc::::;;;;;,,,,'..',,',,,,,,,'..''',;:cloddooxxxxxxkkkxxxkkkxxxkkxxkkkkkkkxxxkxxkkkkkkkkkOOOkkkkkkkkkkOOkkkkkOOOOOOOOOOOkkkkkkkkkkkkOOOOOOOOOOOOOkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxxxxxxddddddddxxxxxxxxxxkkkkkkkkOO00K") + '\n' + 
    string("OkkkkkkOOO00KKKKKXXXXXXXXKKKK0000OOkkxdolccc:,'''.............'''',,,'',,,,;;,;clllclodxdddxxxxdxxxxddddxxxxxkkkkkxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkOOOOOOOOOkkkkkkkkkkkkkkkkkOOOOOOOkkkkkkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxxxxdddddddddddxxxxxxxxxxxxxkkkkOOO00") + '\n' + 
    string("OkkkkkOOOO000KKKKXXXXXXKKKKK000000OOOOkkxdl:;,'...            ....,,'',;;,',,;;:ccccldddoodxxxdddxxxxxdddxxxkkkkxxxxdxxxddooddddxxkkkkkkkkkkOOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOkkkkkkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxxxddddddddddddxxxxxxxxxxxxxxkkkkOO00") + '\n' + 
    string("OkkkkkOOOO00KKKKKXXXXXKKKKK00000000000OOkdc;,,''.....            ......''...',;::cloooddddxxxxdddxxxxxxxxxxkkkxxxxxxxxddddooodddxxkkkOOkkkkkOOOkkkkkkkkkkkkkkkkkkkkkkOOOOOOOOOOkkkkkkkkkkkkkkOOOOOOOOOOOOOOOOOOOOkOOOOOOOOOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxxxxddddddddddddxxxxxxxxxxxxxxxkkkOOO0") + '\n' + 
    string("OkkkkkOOOO0KKKKKXXXXKKKKK000K0000000000Okdc;,'''''........             .   ...',;:clllodxxxdxxxddxxxxxkkkxxxxkxxdxxdddddoooddddxxxxxxkkOkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOOOOOOOOOOOkkkkkkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxxxxddddddddddddddxxxxxxxxxxxxxkkkkkOO") + '\n' + 
    string("OkkkkOOOOO0KKKKKKKKKKKKKK0KKKK00KK000000Oxoc;,,''''.................  .      ....,;:clodddxxxxxxxxxxxkkkxxdddddollolc:ccc::clodxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOOOOOOOOOOkkkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOkkkkkkkkkkkkkkkkkkkkOkkOOOOOOOOOOOOOOOOOOkkkkxxxxxxxxdddddddddddddddxxxxxxxxxxxkkkkkkOO") + '\n' + 
    string("OkkkkkOOOO0KKKKKXXKKKKKKKKKKKKKKKK000000Okxoc:;,,,,'................................,;cllloddxxxxdddddoollc:::;;,,;;,..',',,:lodxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOOOOOOOOkkkkkkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOkkkkkkkkkkkkkkkkkOOOkkkOOOOOOOOOOOOOOOOOOOOOkkkkkkxxxxdddddddddddooodddxxxxxxddddxxxkkkkkkOO") + '\n' + 
    string("OkkkkkOOOO00KKKXXXKKKKKKKKKKKKKKKKK0000OOOkxol:;;;,,''................................'''.':loolc:,,,,,'...........'''.',;::clodxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOOOOOOOOOkkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOkkkkkkkkkkkkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOkkkkkkkxxxxxxddddddddddddddxxxxxxxdddddxxxxkkkkOOO") + '\n' + 
    string("0OOOOOO0000KKKXXXKKKKKKKKKKKKKKKKK0000OOOOOkxdolcc:;,,''....................................,;,'...............''.',,;;;:cloodxxxxxxxkkkkkkkkkkkkkkkkkkkkkkOOOOOOOOOOOOOOOOOOOkkkkkOOOOOOOOOOOOOOOOOOOOOOkkkkkkkkkkkkkkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOkkkkkkkxkxxxxxxxxxddddddddddddxxxxxdddddddxxxxkkkkOOO") + '\n' + 
    string("XKKKKKKKKKKKKXXXXKKKKKKKKKKKKKKK000000OOOOOOkxxxddlc:;,,''''''....''........'''.................'''.''''...'..',,;;::cccclooddxxxkkkkkkkkkkkkkkxxxkkkkkkOOOOOOOOOOOOOOkkkkkkkOOOOOkOOOOOOOOOOOOOOOOOOOOOkkkkkkkkkkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkkkkkkkkkkkxxxxxxddddddddddddddddddddddddddxxxxkkkkOO") + '\n' + 
    string("NXXXXXXXXXXXXXXXXKKKKKKKKKKKKKK0000000000OOOOkkkkxdolc:;;;,,,,''''',,'''''.'','''''............',;,,,;;;,,,;;;;;:::cllloooddxkkkkkkOkkkkkkkkkkkxxxkkkkkOOOOOOOOOkOOOOkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkkkkkkkkkkkkkOOOOOOOOOO000OOOOOOOOOOOOOOOOOOOOOOkkkkkkkkkxxxxxxddddddddddddxxddddddddddddxxxxkkkOO") + '\n' + 
    string("NNNNNNNNNXXXXXXKKKKKKKKKKKKKKKKK0KKKK000000OOOOOkxddollc::;;;;;;;;;:::::::;;:::;;;;,,,''.'''',,,;:::;:::::cccccllcccloodxxxxxkkkkOOOOkkkkkkkkkkkkkkkkkkkkOOOOOOOkkkkkkkOOOOOOOOOOOOOOOkkOOOOOOOOOOOOOOOOOkkkkkkkkkkkOOOOOOOOO000000000000000OOOOOOOOOOOOOOOOkkkkkkkkkxxxxxddddddddxxxxxxddddddddddxxxxkkkkOO") + '\n' + 
    string("NXNNNNNNNNNXXXXKKKKKKKKKKKKKKKKKKKKKKK0000000OOOkkxxddolcc::cccccccccclccccccccccccc:;;;;;;;:ccccllllllllllllllooooooodxxkkxkkkkkkkOOkkkkkkkkkkkkkkkkkkkkkkOOOOOOOOOkkOOOOOkkkkkkkkOOOOOOOOOOOOOOOOOOkkkkkkkkkkkkkkOOOOOOOOO0000000000000000OO0000OOOOOOOOOkkkkkkkkkkxxxdddddddddxxxxxxxdddddddddxxxkkkkkkOO") + '\n' + 
    string("NNNNNNXXXXNNXXXKKKKKKKKKKKKKKKKKKKKK000000000OOOOOkkxxdollccccclllllccccclllooooooolcccccccclooooloooolllllllooooooddxxxxkkkkkkOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOkkkkkkkkkkkkOOOOOOOOOOOOOOOOOOOOkkkkkkkkkkkkkOOOOOOOOOO00000000000OOOOOOOO0OOOO000OOOOOkkkOOkkkkkxxddddddddddddxddddddddxxxxxxxxxxxkkkOO") + '\n' + 
    string("NNNNNNXXXXNNNXXKKKKKKKKKKKKKXKKKKKKK0000000OOOOOOOOkkkxddocclccllllllllllloooddoddddoooollloddddooooooooooddddddddddxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOkkOOOOOOOOOOOOOOOOOOOkkkkOOOOOOkkkkkkkOOOOOOOOOOOOOOOO000000OOOOOOOOOOOOOOOOOOOOOOOOOOOkkkkxxxxxddddxxxxxddddddddddddddxxxxxxxxxxkkkkk") + '\n' + 
    string("NXXXXXXXXXXNNXXXKKKKKKKKKKKKKKKKKK00000000OOOOOOOOOOOOkkkxdoolllooooooooooooddddxxxddddddodddddddddooodddddxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOkkOOOOOOOOOOOOOOOOOOkkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOO0000OOOOOOOOOOOOOOOOOOOOOOOOOOOOkkkkxxxddddddddddddddddddddddddddxxxxxxdxxxkkkkkk") + '\n' + 
    string("NXXXXXXXXXXXXXXXKKKKKXXXXKKKKKKKKK00000000OOOOOOOOOOOOOOOkkxxdddddddxxxxdddddxxxxxxxxxdddddxxxxdddxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOkkkOOOOOOOOOOOOOOOOOOkkkkkOOOOOOOOOOOOOOOOOOOOOOOO0OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkkkkkxxxxxxdddddddoooddddddddddddddxxxxxxdxxxxxxkkkk") + '\n' + 
    string("NXXXXXXXXXXXXXXXXKKKKXXKKKKKKKKKK000000000OO0OOOO000OOOOOOOkkkkkxxkkkkkkkxxxxxxkkkkkxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxxxxxkkkkkkkkkkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkkkkxxxxxxxxxxxddddooodddddddddddddddxddxddxxxxxxxxxk") + '\n' + 
    string("NXXXXXXXXXXXXXXXXXKKKKKKKKKKKK0KK000000000OO0OOO00OOOOOOOOOOOOOOOkkkkkkkkkkkkkkkkkkkkkkkxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxxxkkkkkkkkkkkkkkkkkkxxxxxkkkkkkkkkkOOOOOkOOOOOOOOOOOOOOOOOOOOOOOOOOOkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkkkkkkkkkkkxxxdddddddoooddddddddddddddddddddddxxxxxxxxxk") + '\n' + 
    string("XXXXXXXXXXXXXXXXXXXKKKKKKKKKK00000000000OO0000OO00OOOOOO000OOOOOOOOOOOkkOOOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxxxxxxxxxxxxxkkkkkkkkkxxkkkkkkkkkkkkkkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOkkkOkkkOOOOOkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOkkkkkkkkkkkkkkkkxxxxddddddddddddddddddddooddddodddddxxxxxxxxkk") + '\n' + 
    string("XXXXXXXXXXXXXXXXXXXKKKKKKKKK000000000000000000O000000000OOOO000OOOOOOOkkOOOkkkkkkkkkkkkkkkxxkkkkkkxxxxxxxxxkkkkxxxxxxxxkkxxxxxxxxxxxxxxxxxkkkkkxxxkkkkkkkkkOkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOkkkkkOOkkkkkOOOOOOOOOOOOOOOOOOOOOOkOOOOOkkOOOOkkkkkkkkkkkxxkkkkxxxxxddddddddddddddddddddoooooooooooddddddxxxxxxxx") + '\n' + 
    string("XXXXXXXXXXXXXXXXXXXKKKKKKKK000000000000000000OOO0000000OOOOOO000OOOOOOOkkkkkkkkkkkkkkkkkxxxxxxxxxkkkkkkkxxkkkkkkxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxkkkkkkkOOOkOOOOOOOkkkkkkOOOkOOOOOOOOOOOOOOOOOOOOOOOOOkkkkOkkkOOOOOOOkkkkkkkOkkkkkkkkkkkOOOkkkkkkkxxxxxkkxxxxxddddddddddddddddooodddoooooooooooooooddddxxxxxxx") + '\n' + 
    string("XXXXXXXXXXXXXXXXXXXXKKKKKKKKKKK00000000000000OOO000000OOOOOOOOOOOOOOOOOOOOkkkkkkkkkkkkkkkxxxkkkkkkkxkkkkkkxxxkkkkxxxxxxxxxxxxxxxxxkkkkxxxxxxxxkkkkkOOOOOOOOOOOOOOOkkkkkOOOOOkkkkkkkkkOOOOOOOkkkOOOOOOOOOOOOOOOOOOOOkkkkkkkkkkkOOkkkkkkOOOOOkkkkxxxxxkkkxxxxxddddxxxdddddddddoooooooodddoooooooooddddxxxxxxxx") + '\n' + 
    string("XXXXXXXXXXXXXXXXXXXXKKKKKKKKKKK000000000O000000000OOOOOOkkkkOOOOOOOkkkkkkkkkkkkkkkkkkkkkkxxxxxxxxxkkxxxxxxxxxxxxxxxxxxdddddxxxxxddxxxxxxxxxxxkxxxxxkkkkkkOOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOOOOOOkkkxxxxkkkkkkkkkkkkkkkkkkkkxxxxxxxxxxxxxxxddddddxdxxxxdddddddddoooooooooooooooddddxxxxxxxxx") + '\n' + 
    string("XXXXXXXXXXXXXXXXXXXXKKK00KKKKKK000000000O0000000Okxolccccccclodxxdlc::::::clllcc:ccldxxolc::::::cclollc::::::clddolcccccccccloolc::;;:::cloxkkxolc::::cclllllc:::cllllc::::::cloxkkxolc::::::cclllccccccllodxkkkdolclllllcldddoc::::cclllc:::::clodxxxxxxdddddddddddddddddddddddddoooooolllooooodddddxxxxxxx") + '\n' + 
    string("XXXXXXXXXXXXXXXXXXXKKK00000K000000000000O000000OkocxOOOOOOOOOxo:;:xOOOOOOOOd;cOOOOOd:ll:dOOOOOOOOk:';dOOOOOOOkc;::lx0KXXXK0ko:,:xOOOOOOOOd:cxxlcxOOOOOOOx;,dOOOOOOx::xOOOOOOOOd:lxxlcxOOOOOOOOxclOOOOOOOOOkdlclccok0KXXXKOdc;;oOOOOOOOl'cOOOOOOOo:lxxxxxdddddooooooddddddddxddddddooollolllooooooddddxxxxxxx") + '\n' + 
    string("XXXXXXXXXXXXXXXXXXXKKK0000000000000000000000000Ox::OMMMMMMMMMMNd.,OMMMMMMMM0;oNMMMWx,;;;kWMMMMMMMX:.;0MMMMMMMNl.'oXMMMWWWMMMNd.;KMMMMMMMMk;:dd::OMMMMMMMXc;0MMMMMMK;;KMMMMMMMMk;:dd::OMMMMMMMMKloNMMMMMMMMMW0:.;OWMMMWWWMMW0:.oNMMMMMWx,dWMMMMMNd,cddddddddddddddddddddddddddddoooooollooooooooodddddddddxxx") + '\n' + 
    string("XXXXXXXXXXXXXXXXXXKKKK00OOO00000000000000000000Ox:;OMMMMNkOWMMMK;'OMMMMNOddl'oNMMMWx,;;,xWMMMW0ddo,.cXMMMMMMMWx.'kMMMMKoOWMMMO';KMMMMNkddl:lxd;;OMMMMMMMWxoXMMMMMMK;;0MMMMNkddl:lxd;;OMMMMNOddl;oNMMMW0kXMMMNo.lNMMMWkxXMMMWx,oNMMMMMMOlOMMMMMMNd,:odddddddddddddddddddddddoooooooooooooooooooddddddddddddxx") + '\n' + 
    string("XXXXXXXXXXXXXXXXXKKKKK000OOOOO00000000000000000Ox:;OMMMMKcoNMMMK:'OMMMMX:....oNMMMWx,;;,xWMMMNl..'''dNMMMWMMMMO,'OMMMMKookkkko';KMMMM0, .;ldxd;;OWMMMMMMM0OWMMMMMMK;;0MMMM0,..;lxkd;;OMMMMX:....oNMMMWdc0MMMWd'dWMMMNocKMMMMO,oNMMMMMMXOXMMMMMMNd,:dxxddddddddddddddddddddoooooooooooooooooooodddddxddddddxx") + '\n' + 
    string("XKKXXXXXXXXXXXXXXKKKKK000OOOOOO00000000OOOO0000Ox:;OMMMMN0KWMMWO''OMMMMNOddc'oNMMMWx,;;,xWMMMW0ddo,'kWMMWKXMMMX:.oNMMMMNKx:'...:KMMMMNkddocoxd;;OMMMMMMMMWWMMMMMMMK;;0MMMMNkdxocdkd;;OMMMMNOddc'oNMMMWK0NMMMXc.dWMMMNocKMMMMO;lNMMMMMMWNWMMMMMMNd':odddddddddddddddddddoooooooollloollooooooooddddxxdddddxxx") + '\n' + 
    string("XKKXXXXXXXXXXXXKKKKKK00000OOOOOOO000OOOOOOO0000Ox:;OMMMMMMMMMW0:.'OWMMMMMMWk,oNMMMWx,;;,xWMMMMMMM0;,0MMMXxOWMMNd..l0NMMMMMNKd;.:KMMMMMMMWx;cxd;;OMMMMWWWMMMMMWWMMMK;;0MMMMMMMWx;lxd:;OMMMMMMMWk,oNMMMMMMMMMNd..dWMMMNocKMMMMO;oNMMMWWMMMMMWWMMMNd':odddddddddddddddddooooolllllllllllllooooooddddxddddddxxxx") + '\n' + 
    string("XKKKKXXXXXKKKKKKKKKKK00000OOOOOOOOOOOOOOOOOOOO0Ox:;OMMMMNO0WMMWk''OMMMMW0kkl'oNMMMWx,;;,xWMMMWKkko,cXMMMKoxWMMWO,..':xKWMMMMWk,;KMMMMN0kko:lxd;;OMMMWXKNMMMMWXNMMMK;;0MMMMN0kko:okx:;OMMMMW0kkl'oNMMMWKONMMWK:.dWMMMNocKMMMMO;oNMMMXXWMMMWXXMMMNd,:odddddddddddddddooooollllllllllllllooooooddddxxddddddxxxx") + '\n' + 
    string("XKKKKXXXXKKKKKKKKKKKK00000OOOOOOOOOOOOOOOOOOOO0Ox:;OMMMMXcoNMMMX:,OMMMMXc..'.oNMMMWx',,,xWMMMNo....dWMMMWKXWMMMKclOOOOkd0WMMMXc;0MMMM0;.':ldxd;;OMMMNOxKWMMMXOXMMMK;;0MMMM0;.,cokOx:;OMMMMXc.','oNMMMWdc0MMMWd'dWMMMNocKMMMMO;lNMMMKONMMMN0KWMMNd,:dxddddddddddddooollloollooooooooooooooooddddddddddxxxxxxx") + '\n' + 
    string("XKKKKKKXXXKKKKKKKKKKK000000OOOOOOOOOOOOOOOOOOOOOx:;OMMMMXclNMMMX:,OMMMMXo,;;,oNMMMWk;;,,xWMMMNd,,,:OMMMMMWMMMMMNxkWMMMO;oNMMMNl;0MMMMKc,:clodo;;OMMMNxckWMMMOxXMMMK;;0MMMMKc,:loxkx::OMMMMXc'c:,dNMMMWx:0MMMWd'oWMMMNdlKMMMMO,oNMMM0dKMMMXxOMMMNd,:dxxddddddddooooollllllllllllloooooooodddddddddddddxxxxxkk") + '\n' + 
    string("XKKKKKKKKKKKKKKKKKKKK0000000OOOOOOOOOOOOOOOOOOOOx:;OMMMMXclNMMMX:'OMMMMWNXXKodNMMMMWXXOcxWMMMMNXXXKNMMMMXdxNMMMWOxNMMMNOKWMMMX:;0MMMMWNXX0l;lo;;OMMMNd,oXMMWxoXMMMK;;0MMMMWNXXKo:dd::OMMMMXl,cc,dNMMMWd:0MMMWx.:KMMMWK0NMMMNo'oNMMMOlOMMM0lOMMMNd':odddddddddoooollllllllllllllllooooooddddddddddddddxxkkkkk") + '\n' + 
    string("KKKKKKKKKKKKKKKKKKKKK00000000OOOOOOOOOOOOOOOOOOOxc:OWWWWKclXWWWKc,OWWWWWWWWXddNWWWWWWW0lxNWWWWWWWWNWWWWWk';KWWWW0coKWWMMMMWNKo':0WWWWWWWWXl;lo::OWWWNo':0WWXllXWWW0;;0WWWWWWWWXl;odc:OWWWWXl;ll;dNWWWNd:OWWWNx'.cONWMMMMWWKd'.oNWWWO:dNWWx:OWWWNd,:dddddoooooooooolllllllllllllloooooodddddddddddxxxxxkkkkkk") + '\n' + 
    string("KKKKKKKKKKKKKKKKKKKKK000000000OOOOOOOOOOOOOOkOOOkoclllllc;;lllll:;clccccccll::clccccclc;:llccccccccccccl:,;clcclc;';coddddoc:;;:clccccccllccodl:cllll:',cllc;;lllll;;lllllcclllclxxocllllllclxdlllllll:,clcllc:::;clddddoc:;::cllllc,;lll;,:lcllc:lddddddoooooooooollllllllllloooooodddddxxxxxxxxxxxxxkkkkkk") + '\n' + 
    string("KKKKKKKKKKKKKKKKKKKK0000000000OOOOOOOOOOOOOOkkkkkkxdollooooollloddoollllcllloollccccclloolccccccccccccccloollcccloooc:::::cloddolcccc:ccclodxxdollccloooooooooollloddoollllllooxkkOkxdolllodxkkxdolllloolllllodxxdlc::::ccodddolcclloollllllcccllddxxdddddddooooollllloooooooooooodddxxxxxxxxxxxxxxkkkkkkkkO") + '\n' + 
    string("KKKKKKKKKKKKKKKKK0OkxddoooooooddddoooddddoooooddooloodxkxdollllloodxkkkkxdoollllllllllooollllllllooollcccclloddxddolccccllooolllcclloollcllloollcloddddoooodxxxdoollooodxkkxooooodxkOOOOOkkxdollllllllolllllllllloodxxxxxddolcccccloddddolllloooolllloooolc:;;;;::cllcc::::::::clddxxxxxxxxxxxxxkkkkkkkkOOOO") + '\n' + 
    string("KKKKKKKKKKKKKKKKOdodddoooooooodllododdc:ldoodl;coooodlcccloxkkkxxolcoxkdllooooooooooooc:oooooooooc;looooooooolcc:coooooodo;;looooooo;:looool;:ooooo:;coododocccldooooodolccldooodllokkkOOkdclooooooooccoooooooooodoloxkxdlccoxxkkxdl::::looooc;;looooc:;;cldxxxxdl:;,;lolllllool:cdxxxxxxxxxxxkkkkkkkkOOOOOO") + '\n' + 
    string("KKKKKKKKKKKKKKKKkcc0MMMMMMMMMMW0ONMMMWdc0MMMMO;oNMMMWx',xXWMMMMMMWXx:cdl;oNMMMMMMMMMMNooXMMMMMMMWd;OWMMMMWMWWN0c.;OWMMMMMK:,OMMMMMMK:;KMMMM0:cXMMMNo.l0XMMWO;.;OWMMMMMMXl.'dNMMMWx;cxkkkkxc;dNMMMMMMWO0WMMMMMMMMMW0c:dxd:ckXWMMMMMMN0l.;OWMMWO,,OWMMXl.;xXWMMMMMWWKd',OWMMMMMMM0:;oxkkxxxxxxkkkkkkkkkOOOOOOO") + '\n' + 
    string("KKKKKKKKKKKKKKKKkl:kKXNMMMMMNXKxkNMMMWd:0MMMMO;lNMMMWd.cXMMMW00WMMMXl;ll;l0KXWMMMMWXK0clXMMMMWXKKl,OMMMMWKXWMMMO,'OMMMMMMNocKMMMMMMK;;0MMMM0;:XMMMM0:cOXMMWO,.:KMMMMMMMWd..oNMMMWx,:dkkkxd;;kWMMMMMMWX0KXNMMMMMNXKkc:ddc;xWMMMN0KWMMMK:,OMMMMNo;OMMMX:'xWMMMNOOWMMMNl,OMMMMWNKKk;;oxkkkxxkkkkkkkkkOOOOOkkOOO") + '\n' + 
    string("K0KKKKKKKKKKKKKK0koc;;kWMMMNd,''oNMMMWd:0MMMMO;lNMMMWd.lNMMMNoc0NNNKo;odlc;'cKMMMMKc''.cXMMMWO;.,.,OMMMMXloNMMMK:'OMMMMMMWOxNMMMMMMK;;0MMMM0;:XMMMMWkdOXMMMO'.lNMMMMMMMWO'.oNMMMWx,:dxkkxo,:0MMMMMMMMXl.'dNMMMWk,,:ldxd;:0MMMMKcdWMMMNl,OMMMMMKd0MMMX:,OMMMMK;:XMMMWx;OMMMMXl.';:ldxxxxkkkkkkkkkkOOOOkkkkOOO") + '\n' + 
    string("KKKKKKKKKKKKKKKKKK0x:,xWMMMNo'''oNMMMW0kXMMMMO;lNMMMWd.cXMMMWXOxc;;::ldkkxl':KMMMM0;','lXMMMW0c;:',OMMMMXxkWMMMK;'OWMMMMMMXXWMMMMMMK;;0MMMM0;:XMMMMMNXXNMMMO'.xWMMWNNMMMK;.oNMMMWx,;dxxxxl,lXMMMNNMMMNd..oNMMMWx';oxkko,:0MMMM0:dNMMMNo,OMMMMMWXXMMMX:,0MMMM0;:XMMMMk:OMMMMNo;::codxxkkkkkkkkkOOOOOOOOkkkOOO") + '\n' + 
    string("K0KK000KKKKKKKKKKKKOl;kWMMMNo',,dNMMMMMMMMMMMO;lNMMMWx.'dXMMMMMWKxc,:oxxkxo,:KMMMM0:';,lXMMMMWNNXl,OWMMMMWWMMWKl.'OMMMMMMMMMMMMMMMMK;;0MMMM0;:XMMMMMMMMMMMWk''OMMMNO0MMMNl.oNMMMWx,:dxxxd:'dWMMW0ONMMWk'.oNMMMWx,:dxxxo,;0MMMM0:dNMMMNo,kWMMMMMMMMMMX:,0MMMMK;,oxdddc;OWMMMMWNNk:cdkkkkkkkkOOOOOOOOOOOOOOOOO") + '\n' + 
    string("K0KK000KKKKKKKKKKKKOl;kWMMMNo,,,dNMMMMWWWMMMMO;lNMMMWx'.';oONWMMMMNk:;odxdl,:KMMMM0:';'lXMMMMWNNKc,OWMMMWXNMMWKl.'OMMMWNWMMMMWNWMMMK;;0MMMM0;:XMMMMMMMMMMMWk':XMMMXokWMMWx'oNMMMWx,:dxkxd;;OWMMWxoXMMMK;.oNMMMWx,:dxxxo,;0MMMM0:dNMMMNo,OWMMMMMMMMMMX:,0MMMMK;.....'.,OMMMMWWNNk:cxkkkkkOOOOOOOOOOOOOOOOOOOO") + '\n' + 
    string("K000000K0000KKKKKKKOl;kWMMMNo,,,dNMMMWkoKMMMMO;lNMMMWx.,llldkOKWMMMWd,:oddc':KMMMM0:';'lXMMMM0c;;',OMMMMXodNMMMK;,OMMMN0XMMMMN0NMMMK;;0MMMM0;:XMMMWNMMMMMMWk,lNMMMXk0WMMM0;oNMMMWx,:dkkxo,:KMMMWOkNMMMNl.oNMMMWx,:dkkko,;0MMMM0:dNMMMNo,kMMMWNWMMMMMX:,0MMMMK;;k0000o:OMMMMXo;:cldkOOOOOOOOOOOOOOOOOOOOOOOO0") + '\n' + 
    string("K00000000000KKKKKKKOl;kWMMMNo,,,dNMMMWd:0MMMMO;lNMMMWx.cXMMMXl:KMMMMk,;oddc':KMMMM0;','lXMMMMk'...,OMMMMXclNMMMX:,OMMMNkOWMMM0kXMMMK;;0MMMM0;:XMMM0kNMMMMMWk;xWMMMMMMMMMMXloNMMMWx',coxxc,lXMMMMMMMMMMWx'oNMMMWx,:dkkxo,;0MMMM0cdNMMMNl,OMMMXkKMMMMMX:,OMMMM0;:XMMMWk:kWMMMXc.':oxkOOOOOOOOOOOOOOOOOOOOOOOO0") + '\n' + 
    string("K00000000000KKKKKKKOl;kWMMMNo,,,dNMMMWd:0MMMMO;lNMMMWd.:KMMMNxoXMMMWk,;oddl':KMMMM0;','lXMMMMXkxxocOMMMMXclNMMMX:'OMMMNddNMMWkdXMMMK;;KMMMM0;:XMMMOckWMMMMWkl0MMMMN0KWMMMWxxNMMMMXkxxccl:,xWMMMWK0NMMMM0;oNMMMWx,:xkOkd:;kWMMMXxOWMMMXc,OMMMXloNMMMMX:'xWMMMXodNMMMWo;kMMMMW0xkkocdkOOOOOOOOOOOOOOOOOOOOOOO0") + '\n' + 
    string("K000000000000KKKKKK0l:kWMMMNd,;,dNMMMWd:0MMMMO;lNMMMWx.'xNMMMWWMMMWXl,cdxdl,:KMMMM0:';'lXMMMMMMMM0oOWMMMXclNMMMX:,OMMMNdcKMMNolXMMMK;;KMMMM0;cXMMMO':XMMMMWOdXMMMMO,:KMMMWKONMMMMMMMKl;c;;OMMMMXc,kWMMMXodNMMMWx,cxkOkkl;c0WMMMWWMMWNd.'OMMMX:'kWMMMXc.:0WMMMWWMMMNk,,OMMMMMMMMNd;okOOOOOOOOOOOOOOOOOkkkkOO0") + '\n' + 
    string("K000000000000KKKKXX0dcokkkkklclclkkkkkc;okkkko,:xkkkkl;,;cdO0KKK0kdc;ldxxxo::dkkkkd:;:;cxkkkkkkkko:lkkkkd;:xkkkd;,okkkx:,lkkd;;dkkkd,,dkkkkd,;dkkko''okkkkkolxkkkkl',dkkkkxdxkkkkkkkdccoccdkkkkd;'lkkkkxccxkkkkl:lxkkkkxl::oxOKKK0Odc,';okkkx;.:xkkkxc,;:okOKKK0Oxl;';okkkkkkkkxl:dkOOOOOOOOOOOOOOOOOOOOOOOO") + '\n' + 
    string("K000000000000KKKKKXK0koc:::loxkxoc::::ccc:;::ccc::;::loddl:;;:;:;;:ldxkkkkxdl:;,,;:coolc;,,,,,,,,;;;,,,,;;;,,,,;;;;,,,,;;;,,;;;;,,,;::;;,,;:::;;,;:cc::;;;;;:;;;;:ccc:;;;;:;;;;,;,;;cldxdlc:;;;:ccc:;;;;:::;;;:coxkkkkkkkxoc::::::::cool:;;;:clc::;:coddoc::::::::lodoc:;;;;;;:coxkOOOOOOOOOOOOOOOOOOOOOOOOO") + '\n' + 
    string("K0000000000000KKKXXXXKK000000KK00OOOOOOOOkkkkOOOkkkkkkOOOkxxdooddxxkkkkkkkkxxddddddddxdddoooooooodddooooooooooooooolooooooooooooooodddddddddxxddddxxkkxxxxxxxxxxxxkkkkxxxxxxxxxxxddxxkkkkkkxxxxxxxxxxxxxxxxxxxxxkkkkkkkkkkkkxddddddxxkkxxxxxxkkkkkkkkkOOOkkxxddxxkOOOOOOkkkkkkkkOOO0OO00OOOOOOOOOOOOOOOOOOO0") + '\n';

    cout << doge << endl;

}